services:
  datasource-db:
    image: postgres:15
    container_name: sdek_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DATASOURCE_DB}
      POSTGRES_USER: ${DATASOURCE_USER}
      POSTGRES_PASSWORD: ${DATASOURCE_PASSWORD}
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - db-net
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATASOURCE_USER} -d ${DATASOURCE_DB} -h sdek_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: sdek_backend
    environment:
      - LLM_ID=${LLM_ID}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - OPENAI_API_KET=${OPENAI_API_KET}
      - DATASOURCE_USER=${DATASOURCE_USER}
      - DATASOURCE_PASSWORD=${DATASOURCE_PASSWORD}
      - DATASOURCE_DB=${DATASOURCE_DB}
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    networks:
      - db-net
      - app-net
    depends_on:
     datasource-db:
        condition: service_healthy

  frontend:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: sdek_web
    ports:
      - "5173:5173"
    volumes:
      - ./web:/app
      - /app/node_modules
    networks:
      - app-net
    depends_on:
      - backend

volumes:
  db:
  sdek_backend:

networks:
  db-net:
    driver: bridge
  app-net:
    driver: bridge